default: &default
  adapter: postgresql
  encoding: unicode
  username: fuad
  password: <%= ENV['DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: capstone_development

test:
  <<: *default
  database: capstone_test
