default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: cocacct#2
  pool: 5

development:
  <<: *default
  database: capstone_development

test:
  <<: *default
  database: capstone_test
